spring:
  datasource:
    url: jdbc:mysql://localhost:3306/te
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ab1010
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect